# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
run_lighthouse:
  variables:
    LIGHTHOUSE_TEST_URL: https://www.prettygreen.com
  stage: deploy
  environment: Production
  only:
    - master
  before_script:
    # Install Lighthouse
    - npm i -g lighthouse
  script:
    # Run Lighthouse test
    - lighthouse --chrome-flags="--headless --no-sandbox" $LIGHTHOUSE_TEST_URL --output html --output-path ./report.html
  artifacts:
    paths:
      - ./report.html
    expire_in: 1 week




