version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.1-browsers
    working_directory: /tmp/lighthouse-pg
    steps:
      - attach_workspace:
          at: /tmp/lighthouse-pg
#      - restore_cache:
#          keys:
#            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
#            - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: sudo npm install -g @lhci/cli@0.3.x
      - run:
          name: lhci autorun
          command: |
            lhci autorun --config=./lighthouserc.json